# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8325442dfd328b61d523da8c080b048351a96df748f713f06ffca988dd1abfb50dfd9672fb2b19bc33190e5fc9ee5189c204e5b809ce3ce06fdb1471a3f47916

test:
  secret_key_base: ddaaddf7844fdfecf2f6c88c52fba1b1180220aa1cf492bf3f397cb515182db9fb807707dc1261724cb00c642218224a11ebe732e6cad10bd94132023ef0095c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
